misite/misite/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('req/', include('rare_loading_file.urls')),

]
urlpatterns += i18n_patterns(
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('article/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )

)
if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

misite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (MyLogoutView,
                    get_cookie_view,
                    set_cookie_view,
                    get_session_view,
                    set_session_view,
                    RegisterView,
                    AboutView, UpdateProfileView, ListProfileView)


app_name = 'myauth'
urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True
         ), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('about/<int:pk>', AboutView.as_view(), name='about'),
    path('update/<int:pk>', UpdateProfileView.as_view(), name='update'),
    path('profiles/', ListProfileView.as_view(), name='profiles'),

    path('get_cookie/', get_cookie_view, name='get_cookie'),
    path('set_cookie/', set_cookie_view, name='set_cookie'),

    path('get_session/', get_session_view, name='get_session'),
    path('set_session/', set_session_view, name='set_session'),
]

misite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import shop_index, product_list_view, order_view, create_product, new_order, ProductListView, \
    ProductDetailView, ProductUpdateView, ProductDeleteView, ProductCreateView, OrderListView, OrderDetailView, \
    OrderUpdateView, OrderDeleteView, order_list_json_view, ProductApiViewSet, OrderApiViewSet, LatestProductsFeed, \
    UserOrdersListView, UserOrderJSONView

app_name = 'shopapp'

router = DefaultRouter()
router.register("products", ProductApiViewSet)
router.register("orders", OrderApiViewSet)

urlpatterns = [
    path("", shop_index, name="index"),
    # path('product_list/', product_list_view, name='product_list'),
    # path('order_list/', order_view, name='order_list'),
    # path('create_product/', new_product, name='create_product'),
    path('create_order/', new_order, name='create_order'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_list/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_list/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product_list/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_archive'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),

    path('order_list/', OrderListView.as_view(), name='order_list'),
    path('order_detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_detail/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('order_detail/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('user/<int:pk>/orders/', UserOrdersListView.as_view(), name='user_order'),
    path('user/<int:pk>/orders/export/', UserOrderJSONView.as_view(), name='user_orders_export'),

    path('orders_json/', order_list_json_view, name='orders_json'),

    path('api/', include(router.urls)),
    path("product/latest/feed/", LatestProductsFeed(), name='product-feed'),
]

misite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


def create_path_to_upload_images(instance: 'Profile', name: str) -> str:
    return f'users_files/user_{instance.user.pk}/photos/img_{name}'


class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True, null=True)
    age = models.PositiveSmallIntegerField(blank=True, null=True ,validators=[MinValueValidator(1), MaxValueValidator(120)])
    avatar = models.ImageField(null=False, blank=True, upload_to=create_path_to_upload_images)

    def __str__(self):
        return f'{self.user.first_name or self.user.username}'

misite/myauth/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView, ListView

from .models import Profile


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'

    def get_success_url(self):
        user = self.object
        Profile.objects.create(user=user)
        return reverse('myauth:about', kwargs={'pk': self.object.pk})


class UpdateProfileView(UserPassesTestMixin, UpdateView):
    model = Profile
    fields = 'bio', 'age', 'avatar',

    def get_success_url(self):
        return reverse('myauth:about', kwargs={'pk': self.object.user.pk})

    def get_object(self, queryset=None):
        profile_id = self.kwargs.get('pk')
        return get_object_or_404(Profile, pk=profile_id)

    def test_func(self):
        profile = self.get_object()
        return self.request.user.is_superuser or profile.user == self.request.user


class ListProfileView(ListView):
    queryset = User.objects.select_related('profile').all()
    context_object_name = 'profiles'
    template_name = 'myauth/user_list.html'


class AboutView(DetailView):
    template_name = 'myauth/about_me.html'
    model = User

    def get_object(self, queryset=None):
        user = super().get_object(queryset)
        profile, created = Profile.objects.get_or_create(user=user)
        return user


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f"cookie value:{value!r}")


def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default')
    return HttpResponse(f"session value:{value!r}")


def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spameggs'
    return HttpResponse("session set")

misite/myauth/templates/myauth/about_me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About me
{% endblock %}

{% block body %}
<h1>About me:</h1>

{% if user.is_authenticated %}
    {% if user.profile.avatar %}
        <div>
            <img style="width: 400px" src="{{ user.profile.avatar.url }}" alt="user.profile.avatar.name">
        </div>
    {% else %}
        <p>No avatar upload yet...</p>
    {% endif %}

    <h2>Profile:</h2>
    <p>username: {{ user.username }}</p>
    <p>firstname: {{ user.first_name }}</p>
    <p>lastname: {{ user.last_name }}</p>
    <p>is_superuser: {{ user.is_superuser }}</p>
    <p>bio: {% firstof user.profile.bio|linebreaks 'No bio' %}</p>
    <p>age: {% firstof user.profile.age 'No age' %}</p>
{% else %}
    <p>User is anonymous</p>
{% endif %}
{% if request.user.is_staff or request.user.pk == user.pk %}
    <a href="{% url 'myauth:update' pk=user.profile.pk %}">Update profile</a><br>
{% endif %}
<a href="{% url 'shopapp:index'%}">Back to shop</a><br>
<a href="{% url 'myauth:profiles'%}">Back to user list</a>
{% endblock %}<br>

misite/myauth/templates/myauth/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Home
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        <h1>Home</h1>
    {% endblock %}<br>
</body>
</html>

misite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Войти</button>
</form>

{% endblock %}<br>

misite/myauth/templates/myauth/profile_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update
{% endblock %}

{% block body %}
    <h1>Update:</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

<p><a href="{% url 'myauth:about' pk=object.user.pk %}">Back to about</a></p>
{% endblock %}<br>

misite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>

{% endblock %}<br>

misite/myauth/templates/myauth/user_list.html
{% extends 'myauth/base.html' %}

{% block title %}
    User list
{% endblock %}

{% block body %}
    <h1>User list:</h1>
    {% for user in profiles %}
    <ul>
        <li>
            <a href="{% url 'myauth:about' pk=user.pk %}">{{ user }}</a>
        </li>
    </ul>
    {% empty %}
        <p>Users no yet</p>
    {% endfor %}
<a href="{% url 'shopapp:index'%}">Back to shop</a>
{% endblock %}<br>