misite/misite/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('req/', include('rare_loading_file.urls')),

]
urlpatterns += i18n_patterns(
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('article/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )

)
if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

misite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (MyLogoutView,
                    get_cookie_view,
                    set_cookie_view,
                    get_session_view,
                    set_session_view,
                    RegisterView,
                    AboutView, UpdateProfileView, ListProfileView)


app_name = 'myauth'
urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True
         ), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('about/<int:pk>', AboutView.as_view(), name='about'),
    path('update/<int:pk>', UpdateProfileView.as_view(), name='update'),
    path('profiles/', ListProfileView.as_view(), name='profiles'),

    path('get_cookie/', get_cookie_view, name='get_cookie'),
    path('set_cookie/', set_cookie_view, name='set_cookie'),

    path('get_session/', get_session_view, name='get_session'),
    path('set_session/', set_session_view, name='set_session'),
]

misite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import shop_index, product_list_view, order_view, create_product, new_order, ProductListView, \
    ProductDetailView, ProductUpdateView, ProductDeleteView, ProductCreateView, OrderListView, OrderDetailView, \
    OrderUpdateView, OrderDeleteView, order_list_json_view, ProductApiViewSet, OrderApiViewSet, LatestProductsFeed, \
    UserOrdersListView, UserOrderJSONView

app_name = 'shopapp'

router = DefaultRouter()
router.register("products", ProductApiViewSet)
router.register("orders", OrderApiViewSet)

urlpatterns = [
    path("", shop_index, name="index"),
    # path('product_list/', product_list_view, name='product_list'),
    # path('order_list/', order_view, name='order_list'),
    # path('create_product/', new_product, name='create_product'),
    path('create_order/', new_order, name='create_order'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_list/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_list/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product_list/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_archive'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),

    path('order_list/', OrderListView.as_view(), name='order_list'),
    path('order_detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_detail/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('order_detail/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('user/<int:pk>/orders/', UserOrdersListView.as_view(), name='user_order'),
    path('user/<int:pk>/orders/export/', UserOrderJSONView.as_view(), name='user_orders_export'),

    path('orders_json/', order_list_json_view, name='orders_json'),

    path('api/', include(router.urls)),
    path("product/latest/feed/", LatestProductsFeed(), name='product-feed'),
]

misite/shopapp/models.py
import decimal

from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField(max_length=2000, blank=True)
    price = models.DecimalField(default=decimal.Decimal('0.00'), max_digits=10, decimal_places=2, blank=False,
                                null=False)
    discount = models.PositiveSmallIntegerField(default=0)
    create_date = models.DateTimeField(auto_now_add=True)
    is_archive = models.BooleanField(default=False)
    created_by = models.ForeignKey(to=User, on_delete=models.PROTECT, related_name='products')
    count = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def __str__(self):
        return f"product {self.name}"

    def get_absolute_url(self):
        return reverse("shopapp:product_detail", kwargs={"pk": self.pk})

    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + '...'


class Order(models.Model):
    address = models.CharField(max_length=255, blank=False, null=False)
    comment = models.TextField(max_length=500, blank=True, null=False)
    create_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(to=User, on_delete=models.PROTECT, related_name='orders')
    promocode = models.CharField(max_length=10, blank=True, null=False)
    products = models.ManyToManyField(to=Product, related_name='orders')

    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')

    def __str__(self):
        return f"delivery address {self.address}"

misite/shopapp/forms.py
from django import forms
from .models import Product, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "description", "price", "discount",


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "address", "comment", "user", "products"


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

misite/shopapp/views.py
import json
import logging
import random
from pprint import pprint

from timeit import default_timer

from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.cache import cache
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from rest_framework.viewsets import ModelViewSet

from .forms import ProductForm, OrderForm
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, redirect, reverse

from .models import Product, Order
from rest_framework.response import Response
from rest_framework.request import Request

from .serializers import ProductSerializer, OrderSerializer

from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from django.contrib.syndication.views import Feed

logger = logging.getLogger(__name__)


def shop_index(request: HttpRequest):
    rand_num = random.randint(0, 50)
    products = [
        ('laptop', 1900),
        ('desktop', 2900),
        ('phone', 500),
    ]
    context = {
        'rand_num': rand_num,
        'products': products
    }
    logger.info(f'open this view with products: {products}')
    return render(request, 'shopapp/shop-index.html', context=context)


def product_list_view(request: HttpRequest):
    products = Product.objects.all()

    context = {
        'products': products
    }
    return render(request, 'shopapp/product_list.html', context=context)


def order_view(request: HttpRequest):
    orders = Order.objects.select_related('user').prefetch_related('products').all()

    context = {
        'orders': orders
    }
    return render(request, 'shopapp/order_list.html', context=context)


def create_product(request: HttpRequest):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            url = reverse('shopapp:product_list')
            return redirect(url)
    if request.method == 'GET':
        context = {
            'form': form
        }
        return render(request, 'shopapp/create_product.html', context)


def new_order(request: HttpRequest):
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            url = reverse('shopapp:order_list')
            return redirect(url)
    if request.method == 'GET':
        context = {
            'form': form
        }
        return render(request, 'shopapp/create_order.html', context)


class ProductListView(ListView):
    model = Product
    queryset = Product.objects.filter(is_archive=False)


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    permission_required = 'shopapp.change_product'
    model = Product
    fields = 'name', 'description', 'price', 'discount', 'count',
    template_name_suffix = '_update'

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        self.object = self.get_object()

        has_edit_perm = self.request.user.has_perm("shopapp.change_product")
        created_by_current_user = self.object.created_by == self.request.user
        return has_edit_perm and created_by_current_user

    def get_success_url(self):
        return reverse('shopapp:product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:product_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.is_archive = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'shopapp.add_product'
    model = Product
    fields = 'name', 'description', 'price', 'discount', 'count',
    success_url = reverse_lazy('shopapp:product_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class OrderListView(ListView):
    queryset = (Order.objects.select_related('user').prefetch_related('products'))
    context_object_name = 'orders'


class OrderDetailView(DetailView):
    queryset = (Order.objects.select_related('user').prefetch_related('products'))


class OrderUpdateView(UpdateView):
    model = Order
    fields = 'address', 'comment', 'user', 'products',
    template_name = 'shopapp/order_update.html'

    def get_success_url(self):
        return reverse('shopapp:order_detail', kwargs={'pk': self.object.pk})


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:order_list')


@user_passes_test(lambda u: u.is_staff, login_url='/shop/')
def order_list_json_view(request: HttpRequest) -> HttpResponse:
    orders = Order.objects.select_related('user').prefetch_related('products').all()
    data = {
        'orders': [
            {'id': order.pk, 'address': order.address, 'promocode': order.promocode, 'user_id': order.user.pk,
             'products_id': [pk.pk if order.products else None for pk in order.products.all()]} for order in
            orders]}
    return JsonResponse(data)


class ProductApiViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = (SearchFilter, OrderingFilter)
    search_fields = ['name', 'price']
    ordering_fields = ['price', 'created_by']
    ordering = ['price']


class OrderApiViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = (DjangoFilterBackend, OrderingFilter)
    filterset_fields = ('address',
                        'comment',
                        'create_date',
                        'user',
                        'promocode',
                        'products',)
    ordering_fields = ['address', 'create_date']
    ordering = ['address']


class LatestProductsFeed(Feed):
    title = 'Продукты'
    link = reverse_lazy('shopapp:product_list')
    description = "Обновления последних продуктов."

    def items(self):
        return Product.objects.filter(is_archive=False).order_by('create_date')

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:50]


class UserOrdersListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'shopapp/user_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        user_pk = self.kwargs.get('pk')
        orders = Order.objects.filter(user=user_pk).prefetch_related('user', 'products')
        return orders

    def get_context_data(self, **kwargs):
        user_pk = self.kwargs.get('pk')
        try:
            user = User.objects.get(pk=user_pk)
        except User.DoesNotExist:
            raise Http404("Пользователь не найден")

        context = super().get_context_data(**kwargs)
        context['current_user'] = user
        return context


class UserOrderJSONView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404("Пользователь не найден")
        data = cache.get(user.pk)
        if data is None:
            orders = Order.objects.filter(user=user).prefetch_related('user', 'products').order_by('pk')

            data = [
                {'pk': order.pk,
                 'user': order.user.username,
                 'address': order.address,
                 'products': [product.name for product in order.products.all()]}
                for order in orders]
            cache.set(pk, data, timeout=300)
        return JsonResponse(data=data, safe=False)

misite/shopapp/templates/shopapp/create_order.html
{% extends 'shopapp/base.html' %}

{% block title %}
New Order
{% endblock %}


{% block body %}
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">
            Save
        </button>
    </form>

</div>
{% endblock %}

misite/shopapp/templates/shopapp/create_product.html
{% extends 'shopapp/base.html' %}

{% block title %}
New Product
{% endblock %}


{% block body %}
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">
            Save
        </button>
    </form>

</div>
{% endblock %}

misite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
Delete Order
{% endblock %}

{% block body %}

<h1>Вы уверены что хотите удалить заказ № {{object.id}}?</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Delete</button>
    </form>
</div>
<div>
    <a href="{% url 'shopapp:order_detail' pk=object.id %}">back_to_order</a>
</div>
{% endblock %}

misite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}


{% block title %}
Order list
{% endblock %}

{% block body %}

<h1>Order list:</h1>
<ol>

    {% for order in orders %}
    <a href="{% url 'shopapp:order_detail' pk=order.id%}">Order # {{order.id}}</a>
    <li>Order delivery address: {{ order.address }} for {{ order.user }}</li>

    <br>


    {% endfor %}

</ol>

{% endblock %}

misite/shopapp/templates/shopapp/order_update.html
{% extends 'shopapp/base.html' %}

{% block title %}
Update Order
{% endblock %}


{% block body %}
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">
            Save
        </button>
    </form>

</div>
{% endblock %}

misite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import-orders-csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

misite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
Arcive Product
{% endblock %}

{% block body %}

<h1>Вы уверены что хотите удалить {{product.name}}?</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Delete</button>
    </form>
</div>
<div>
    <a href="{% url 'shopapp:product_detail' pk=product.id %}">back_to_product</a>
</div>
{% endblock %}

misite/shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
{% translate 'Product detail' %}
{% endblock %}

{% block body %}

<h1>{% translate 'Product' %} # {{product.id}}:</h1>
<div>

    <p>{% translate 'Product name' %}: {{ product.name }}</p>
    <p>{% translate 'Description' %}: {{product.description}}</p>
    <p>{% translate 'Price' %}: {{product.price}}</p>
    {% if product.discount %}
        <p>{% translate 'Discount' %}: {{product.discount}}</p>
    {% else %}
        <p>{% translate 'No discount' %}</p>
    {% endif%}

    {% blocktranslate count product_count=product.count %}
        There is one product.name
        {% plural %}
        There are {{ product_count }} products
    {% endblocktranslate %}

    <p>{% translate 'Is archive' %}: {{product.is_archive}}</p>
    <p>{% translate 'Created by' %}: {{product.created_by}}</p>

</div>
{% url 'shopapp:product_list' as product_list %}
{% url 'shopapp:product_update' pk=product.id as product_update %}
{% url 'shopapp:product_archive' pk=product.id as product_archive %}
{% blocktranslate %}
    <a href="{{ product_list }}">back to products</a><br>
    <a href="{{ product_update }}">update_product</a><br>
    <a href="{{ product_archive }}">product_archive</a>
{% endblocktranslate %}
{% endblock %}

misite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
Create Product
{% endblock %}


{% block body %}
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">
            Save
        </button>
    </form>

</div>
{% endblock %}

misite/shopapp/templates/shopapp/product_list.html
{% extends 'shopapp/base.html' %}


{% block title %}
Product list
{% endblock %}

{% block body %}

    <h1>Product list:</h1>
    <ol>

        {% for product in product_list %}
            <li><a href="{% url 'shopapp:product_detail' pk=product.id %}">{{ product.name }}</a> for ${{ product.price }}</li>
        {% endfor %}

    </ol>

{% if perms.shopapp %}
    {% if perms.shopapp.add_product %}
        <a href="{% url 'shopapp:create_product' %}">create_product</a>
    {% endif %}
{% endif %}



{% endblock %}

misite/shopapp/templates/shopapp/product_update.html
{% extends 'shopapp/base.html' %}

{% block title %}
Update Product
{% endblock %}


{% block body %}
<div>
    <h3>Created by: {{ product.created_by }}</h3>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">
            Save
        </button>
    </form>

</div>
{% endblock %}

misite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
Shop Index
{% endblock %}

{% block body %}
<div>
    <h1>Hello Shop Index!</h1>
</div>


<div>
    <ul>
        {% for name, price in products %}
        <li>
            {{ name | lower }} for $ {{ price | add:1 }} {{ products | last }}
        </li>
        {% if name|length_is:'6' %}
        <p>laptop</p>
        {% endif %}


        {% empty %}
        No products here
        {%endfor%}
    </ul>
</div>
<div>
    Time running: {{ time_running }}
</div>
<div>
    {% lorem 3 p random %}
</div>
{% endblock %}

misite/shopapp/templates/shopapp/urls_list.html
<h1>Urls list:</h1>
<div style="display: flex; gap: 15px">
    <div><a style="text-decoration: none; color: brown" href="{% url 'shopapp:product_list'  %}">Product list</a></div>
    <div><a style="text-decoration: none; color: brown" href="{% url 'shopapp:order_list'  %}">Order list</a></div>
    <div><a style="text-decoration: none; color: brown" href="{% url 'shopapp:index'  %}">Test url</a></div>
    <div><a style="text-decoration: none; color: brown" href="{% url 'shopapp:create_order' %}">create_order</a></div>
    <div><a style="text-decoration: none; color: brown" href="{% url 'myauth:about' pk=user.pk %}">About</a></div>
    <div><a style="text-decoration: none; color: brown" href="{% url 'myauth:profiles' %}">Profiles</a></div>
    <div><a style="text-decoration: none; color: brown" href="{% url 'myauth:logout' %}">Выйти</a></div>
</div>

misite/shopapp/templates/shopapp/user_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    User's orders
{% endblock %}


{% block body %}
    {% if orders %}
        <h1>User {% firstof current_user.first_name current_user.username %} create next orders </h1>
        {% cache 300 user_orders_cache_key current_user.pk %}
            <div>
                <ul>
                    {% for order in orders %}
                       <li>
                            {{ order }}
                           <ul>
                               {% for product in order.products.all %}
                               <li>
                                   {{ product }}
                               </li>
                               {% endfor %}
                           </ul>

                       </li>
                    {% endfor %}
                </ul>
            </div>
        {% endcache %}
    {% else %}
        <h1>User {% firstof current_user.first_name current_user.username %} don't have orders </h1>
    {% endif  %}
{% endblock %}